create table if not exists public.ot_forum_posts (
  id bigint generated by default as identity primary key,
  author_name text not null default 'Anonymous' check (char_length(btrim(author_name)) between 1 and 32),
  category text not null default 'general' check (category in ('general','music','era','live','photos','questions')),
  language text not null default 'ja' check (language in ('ja','en','es','ru')),
  title text not null check (char_length(title) between 3 and 120),
  body text not null check (char_length(body) between 1 and 5000),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ot_forum_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.ot_forum_posts(id) on delete cascade,
  author_name text not null default 'Anonymous' check (char_length(btrim(author_name)) between 1 and 32),
  language text not null default 'ja' check (language in ('ja','en','es','ru')),
  body text not null check (char_length(body) between 1 and 2000),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ot_forum_posts_created_idx on public.ot_forum_posts(created_at desc);
create index if not exists ot_forum_posts_category_created_idx on public.ot_forum_posts(category, created_at desc);
create index if not exists ot_forum_comments_post_created_idx on public.ot_forum_comments(post_id, created_at asc);

alter table public.ot_forum_posts enable row level security;
alter table public.ot_forum_comments enable row level security;

revoke all on public.ot_forum_posts from anon, authenticated;
revoke all on public.ot_forum_comments from anon, authenticated;
grant select, insert on public.ot_forum_posts to anon, authenticated;
grant select, insert on public.ot_forum_comments to anon, authenticated;
grant usage, select on sequence public.ot_forum_posts_id_seq to anon, authenticated;
grant usage, select on sequence public.ot_forum_comments_id_seq to anon, authenticated;

drop policy if exists "ot forum posts public read visible" on public.ot_forum_posts;
drop policy if exists "ot forum posts anonymous insert" on public.ot_forum_posts;
drop policy if exists "ot forum comments public read visible" on public.ot_forum_comments;
drop policy if exists "ot forum comments anonymous insert" on public.ot_forum_comments;

create policy "ot forum posts public read visible" on public.ot_forum_posts
for select to anon, authenticated using (is_hidden = false);

create policy "ot forum posts anonymous insert" on public.ot_forum_posts
for insert to anon, authenticated with check (
  is_hidden = false
  and char_length(btrim(author_name)) between 1 and 32
  and char_length(title) between 3 and 120
  and char_length(body) between 1 and 5000
);

create policy "ot forum comments public read visible" on public.ot_forum_comments
for select to anon, authenticated using (is_hidden = false);

create policy "ot forum comments anonymous insert" on public.ot_forum_comments
for insert to anon, authenticated with check (
  is_hidden = false
  and char_length(btrim(author_name)) between 1 and 32
  and char_length(body) between 1 and 2000
);
